# Generated by Django 5.2.9 on 2025-12-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('storage_capacity', models.CharField(help_text='e.g. 500,000kg', max_length=50)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('CLOSED', 'Closed')], default='RUNNING', max_length=10)),
                ('availability', models.CharField(choices=[('ACTIVE', 'Active'), ('AVAILABLE', 'Available'), ('FULL', 'Full')], default='AVAILABLE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
