# Generated by Django 5.2.9 on 2026-01-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight in kg', max_digits=10),
        ),
    ]
