# Generated by Django 5.2.9 on 2025-12-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('DRIVER', 'Driver'), ('DISPATCHER', 'Dispatcher'), ('ADMIN', 'Admin')], default='CLIENT', max_length=15),
        ),
    ]
